## Importing Required Libraries

In [7]:
import pandas as pd
from sklearn.linear_model import LinearRegression

## Loading Data

In [17]:
df = pd.read_csv('data.csv', skipinitialspace=True)

## Linear Regression

In [18]:
df

number_of_hours_spend_driving  risk_score
0                             10          95
1                              9          80
2                              2          10
3                             15          50
4                             10          45
5                             16          98
6                             11          38
7                             16          93

In [36]:
X, y = df['number_of_hours_spend_driving'].to_numpy(), df['risk_score'].to_numpy()

In [37]:
print(X)

[10  9  2 15 10 16 11 16]


The Linear Regression model expects a 2D array, so we need to reshape the X array.

In [38]:
X = X.reshape(-1, 1) 

In [39]:
print(X)

[[10]
 [ 9]
 [ 2]
 [15]
 [10]
 [16]
 [11]
 [16]]


In [40]:
print(y)

[95 80 10 50 45 98 38 93]


In [41]:
linear_reg = LinearRegression()

In [45]:
linear_reg.fit(X, y)

LinearRegression()

In [46]:
linear_reg.coef_

array([4.58789861])

In [47]:
linear_reg.intercept_

12.584627964022907

Hence, the required equation of the line is `Y = 4.587*X + 12.584`.