## Loading Required Libraries

In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

## Loading Data

KNeighborsClassifier Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df

x  y  type
0  2  4     0
1  4  2     0
2  4  4     1
3  4  6     0
4  6  2     1
5  6  4     0

In [6]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)

In [10]:
X = df.drop(columns=['type'])
X = X.to_numpy()

In [11]:
print(X)

[[2 4]
 [4 2]
 [4 4]
 [4 6]
 [6 2]
 [6 4]]


In [12]:
y = df['type'].to_numpy()

In [13]:
print(y)

[0 0 1 0 1 0]


In [14]:
knn_classifier.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [19]:
X_test = np.array([6,6])


In [21]:
print(X_test)

[6 6]


In [22]:
X_test = X_test.reshape(1, -1)
print(X_test)

[[6 6]]


In [23]:
knn_classifier.predict(X_test)

array([0])

##### Distance Weighted KNN

In [24]:
d_knn_classifier = KNeighborsClassifier(n_neighbors=3, weights='distance')

In [25]:
d_knn_classifier.fit(X, y)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [26]:
d_knn_classifier.predict(X_test)

array([0])